### ISSUE TITLE
Implement SQLite database for dose logs

### ISSUE THREAD

**Issue by prdes** [mogad0n/Tripsit#1]

**Comment by adlai** [comment]
Is the current system the [TripSit/idosev2](https://github.com/TripSit/idosev2) repository?

**Comment by prdes** [comment]
Yes that is where I push stuff when it reaches a certain stage.
I'm closing this anyway because pickled jsons are better in this build. 
And for the actual idosev2 I will be getting this to talk to a Postgres db
